# Generated by Django 5.0.1 on 2026-04-10 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_canalventa_categoriaproducto_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='venta',
            field=models.OneToOneField(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, to='Login.venta'),
        ),
    ]
