# Generated by Django 5.0.1 on 2026-04-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_alter_pago_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Vendedor', 'Vendedor'), ('Usuario', 'Usuario')], default='Usuario', max_length=20),
        ),
    ]
