# Generated by Django 5.0.1 on 2026-04-23 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_alter_usuario_nombre_completo_alter_usuario_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='numero_nota',
            new_name='numero_documento',
        ),
        migrations.AddField(
            model_name='compra',
            name='tipo_documento',
            field=models.CharField(choices=[('Factura', 'Factura Legal'), ('Nota de Venta', 'Nota de Venta'), ('Recibo', 'Recibo'), ('Referencia Libre', 'Referencia Libre / Comprobante Informal')], default='Factura', max_length=20),
        ),
        migrations.AddField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(default='Activo', max_length=10),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nit_documento',
            field=models.CharField(default='0', max_length=20, unique=True, verbose_name='NIT o Documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo',
            field=models.CharField(choices=[('Natural', 'Persona Natural'), ('Empresa', 'Empresa/Jurídica')], default='Empresa', max_length=10),
        ),
        migrations.AlterField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='Login.proveedor'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completado', 'Completado'), ('Rechazado', 'Rechazado')], default='Completado', max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='ReclamoProveedor',
            fields=[
                ('id_reclamo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('motivo', models.TextField()),
                ('fecha_reclamo', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Resuelto (Garantía)', 'Resuelto (Garantía)'), ('Devuelto', 'Devuelto al Proveedor'), ('Rechazado', 'Rechazado por Proveedor')], default='Pendiente', max_length=25)),
                ('resolucion', models.TextField(blank=True, null=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos', to='Login.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamos', to='Login.proveedor')),
            ],
            options={
                'db_table': 'reclamo_proveedor',
            },
        ),
    ]
