# Generated by Django 5.0.1 on 2026-04-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_rename_numero_nota_compra_numero_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='numero_documento',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='compra',
            unique_together={('proveedor', 'numero_documento')},
        ),
    ]
